### ISSUE TITLE
Question 2 : Data Analytic

### ISSUE THREAD

**Issue by jampongsathorn** [jampongsathorn/SCG-IT-DEVELOP#1]
2.2 From question 2.1, Please find the correlation between products for Customer R44.

<img width="1173" alt="R44-Customer-Analysis" src="https://github.com/jampongsathorn/SCG-IT-DEVELOP/assets/85749998/1621254b-1777-4e4b-be62-f2d1d7593f95">

**Comment by akshaykumarkona** [comment]
Hello, I'm willing to contribute to this project. You can check my GitHub portfolio for your reference.
